name: games_for_bored_people
description: Games!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  awesome_flutter_extensions: ^1.2.0
  flex_color_scheme: ^7.3.1
  flame: ^1.16.0
  flame_audio: ^2.10.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.10
  flutter_smart_dialog: ^4.9.3+2
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  logging: ^1.2.0
  nes_ui: ^0.17.0
  provider: ^6.1.1
  recase: ^4.1.0
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  video_player: ^2.8.2
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  flutter_lints: ^3.0.1
  flame_test: 1.0.0

  flutter_animate: ^4.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/achievement_images/
    - assets/magic_8_ball/images/
    - assets/puzzle_game/puzzle_pieces/
    - assets/movie_theater/
    - assets/dexter_hill/audio/
    - assets/dexter_hill/images/
    - assets/dexter_hill/images/dexter_images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: Press Start 2P
#      fonts:
#        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
