name: games_for_bored_people
description: Games!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  awesome_flutter_extensions: ^1.2.0
  clipboard: ^0.1.3
  url_launcher: ^6.3.0
  flex_color_scheme: ^7.3.1
  shared_preferences: ^2.3.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  flutter_smart_dialog: ^4.9.3+2
  sprite: ^0.0.3
  go_router: ^14.2.6
  google_fonts: ^6.2.1
  logging: ^1.2.0
  nes_ui: ^0.20.0
  provider: ^6.1.2
  recase: ^4.1.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  flutter_lints: ^4.0.0
  flutter_markdown: ^0.7.3+1
  syncfusion_flutter_pdfviewer: ^26.2.13
  just_audio: ^0.9.39
  pdfx: ^2.7.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/clicker_game/
    - assets/collectables/
    - assets/achievement_images/
    - assets/extraterrestrial_extermination/
    - assets/puzzle_game/puzzle_pieces/
    - assets/tic_tac_toe/icons/
    - assets/dexter_hill/audio/
    - assets/dexter_hill/images/
    - assets/dexter_hill/images/dexter_images/
    - assets/dexter_hill/images/story_pages/
    - assets/pdf/
    - assets/quizzez/images/
    - assets/quizzez/text/
    - assets/quizzez/images/dinosaurs/
    - assets/quizzez/images/space/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  fonts:
    - family: Merienda
      fonts:
        - asset: assets/quizzez/fonts/Merienda/static/Merienda-Regular.ttf
    - family: TicTacToe
      fonts:
        - asset: assets/quizzez/fonts/tictactoe/TicTacToe.ttf
    - family: DinoSauce
      fonts:
        - asset: assets/quizzez/fonts/dinosauce/DinosauceFont-Regular.ttf
    - family: Erasaur
      fonts:
        - asset: assets/quizzez/fonts/erasaur/Erasaur-wjZ9.otf
    - family: Induction
      fonts:
        - asset: assets/quizzez/fonts/Induction/Induction.otf
    - family: Andromeda
      fonts:
        - asset: assets/quizzez/fonts/Andromeda/AndromedaTV.ttf
    - family: Nebulous
      fonts:
        - asset: assets/extraterrestrial_extermination/fonts/nebulous-font/NebulousRegular-54aV.ttf
    #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
